# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0b9ea2bafedddb484d8427e31c33e310c94a1ad1d36ddf53b2c86d5fe8c6d71ead51bed4a9e9376ca27a78d0be24bbed7e9c64d53283b8fdd6d40a0753fd3e

test:
  secret_key_base: 457d7164ca539abbf50df50839d84f52278dc413391e32315df414e4036c11b9daf3d7a9f84c672d56fb9aa2ff764126bf18c1346bc68801048c25ec143839b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
