# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Last_Last',
            field=models.CharField(max_length=45),
        ),
    ]
