# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historicalStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('win_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pts_for', models.IntegerField()),
                ('pts_against', models.IntegerField()),
                ('champ_wins', models.IntegerField()),
                ('champ_losses', models.IntegerField()),
                ('champ_win_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
                ('position', models.CharField(max_length=12)),
                ('ability', models.DecimalField(decimal_places=3, max_digits=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.IntegerField()),
                ('away_team', models.IntegerField()),
                ('home_score', models.IntegerField(blank=True, default=None, null=True)),
                ('away_score', models.IntegerField(blank=True, default=None, null=True)),
                ('result', models.IntegerField(blank=True, default=None, null=True)),
                ('week_num', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfTeams', models.IntegerField()),
                ('myTeam', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('season_num', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('win_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pts_for', models.IntegerField()),
                ('pts_against', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('ability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team_num', models.IntegerField()),
                ('image_tag', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sportapp.Team'),
        ),
    ]
