# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78a875b046895c10d7d9a18e7b2f63cf08ad4b2de411daffb64d71c675e1d5d876c26445d726bf8ef8a4279133722e82fe5d0690ba340bb1bfc367b64f36027e

test:
  secret_key_base: e4522032267b7567f000c795f7f21265c41462e4f892a806f8064bb463a5578c2b5f7d34aabae1cc6093cbca2b8f2c75b71524dbff601d8390c7b7d75c0e295b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
