# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
