# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07efc62b735a82920dc995bd0c6580fa67f9824ee7c28c44f27e624e2434add3a408a86bc7612202e7637cf899172a221993eacf8365965de32b93fead049d54

test:
  secret_key_base: 63d9fadc7c10126eb55dc60c135055b3e51d6b3ee31f032d93d7725c148a0ec9ec6fbc09594f65c533c0d10820afc7cca26cc291cc119ac7b13dd7846078735a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
