# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e77306e0e99c7ad44fe26b2b5c3176729ad4df67b97a2e08a4cf8ba931b64b7af2bbf4705246f4287c05ee3e343a84923f7699026801e97b72dfb17c12ec97be

test:
  secret_key_base: 690f0962a7adcbc1905c7e1e1d0daddc17640f64912764289f516f75fbada954676610ac39cc2feafa05bc37f8a1066a7d1a972236057658cfd04a498254c4c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
